export enum RiskCategory {
  CYBERSECURITY = 'CYBERSECURITY',
  OPERATIONAL = 'OPERATIONAL',
  THIRD_PARTY = 'THIRD_PARTY',
  COMPLIANCE = 'COMPLIANCE',
  PRIVACY = 'PRIVACY',
  BUSINESS_CONTINUITY = 'BUSINESS_CONTINUITY',
  FINANCIAL = 'FINANCIAL',
  OTHER = 'OTHER'
}

export enum RiskStatus {
  OPEN = 'OPEN',
  UNDER_TREATMENT = 'UNDER_TREATMENT',
  ACCEPTED = 'ACCEPTED',
  CLOSED = 'CLOSED'
}

export enum RiskRating {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  VERY_HIGH = 'VERY_HIGH',
  CRITICAL = 'CRITICAL'
}

export enum RiskHistoryEventType {
  RISK_CREATED = 'RISK_CREATED',
  RISK_UPDATED = 'RISK_UPDATED',
  ASSET_LINKED = 'ASSET_LINKED',
  ASSET_UNLINKED = 'ASSET_UNLINKED',
  CONTROL_LINKED = 'CONTROL_LINKED',
  CONTROL_UNLINKED = 'CONTROL_UNLINKED',
  TREATMENT_CREATED = 'TREATMENT_CREATED',
  STATUS_CHANGED = 'STATUS_CHANGED',
  RISK_RECALCULATED = 'RISK_RECALCULATED'
}
